name: home_page
description: "A new Flutter project."

# Projenizin pub.dev'e yüklenmesini engelleyen satır. Eğer paylaşmak isterseniz, bu satırı kaldırın.
publish_to: 'none'

# Uygulamanızın sürüm bilgisi.
version: 1.0.0+1

# Dart ve Flutter SDK gereksinimlerini belirtir.
environment:
  sdk: ">=3.5.0 <4.0.0"

# Projenizin ihtiyaç duyduğu bağımlılıkları burada tanımlayın.
dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.2.0
  path: ^1.8.3
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  flutter_secure_storage: ^9.2.2
  flutter_local_notifications: ^18.0.1
  flutter_timezone: ^4.0.0
  permission_handler: ^11.4.0
  device_info_plus: ^11.2.0
  shared_preferences: ^2.3.5
  http: ^1.3.0
  intl: ^0.20.2
  connectivity_plus: ^6.1.3
  flutter_rating_bar: ^4.0.1
  file_picker: ^9.0.2
  firebase_storage: ^12.4.4
  cloud_firestore: ^5.6.5
  flutter_downloader: ^1.12.0
  firebase_auth: ^5.5.1
  image_picker: ^1.1.2
  firebase_core: ^3.12.1
  sqflite_common_ffi: ^2.3.5
  timezone: ^0.10.0




# Geliştirme sırasında kullanılan bağımlılıklar.
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Flutter'a özgü ayarlar.
flutter:
  # Material tasarım ikonlarının kullanılmasını sağlar.
  uses-material-design: true

  # Varlık dosyalarını tanımlamak için bu kısmı kullanabilirsiniz.
  assets:
    - assets/images/agu-logo.png
    - assets/images/Canvas_logo_single_mark.png
    - assets/images/images.png
    - assets/images/unnamed.png
    - assets/images/logo_b9P6R8CU.png
    - assets/images/Abdullah_Gul_University_logo.png
    - assets/images/agu_kilit_ekrani.jpg
    - assets/images/gelistiriciler/yunus_baskan.jpg
    - assets/images/gelistiriciler/turgut_alp.jpg
    - assets/images/gelistiriciler/karakose.jpg
    - assets/images/gelistiriciler/mustafa_bicer.jpg
    - assets/images/calendars/2.png
    - assets/images/calendars/4.png
    - assets/images/calendars/schedule2.png
    - assets/images/calendars/schedule1.png

    

